### ISSUE TITLE
Received a System.ArgumentOutOfRangeException on fresh install (windows terminal - powershell)

### ISSUE THREAD

**Issue by meowjesty** [ajeetdsouza/zoxide#327]
1. Installed zoxide with `cargo install zoxide --locked`;
2. Tried `z <CTRL><SPACE>`  on home directory;
- `$PSversionTable`:

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- Windows Terminal, not sure how to check version of this though, it's probably the latest release;

- Error:

<details>

<summary>show error</summary>

```powershell
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 3 Keys:
 z Space Ctrl+Space

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -19.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

</details>

**Comment by ajeetdsouza** [comment]
This is a bug in PSReadLine that appears to have been fixed: https://github.com/PowerShell/PSReadLine/issues/1306. The issue has instructions for how to upgrade.

**Comment by meowjesty** [comment]
Powershell 7 doesn't have this issue, I'll be using it instead.
